# Generated by Django 5.1.5 on 2025-02-27 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_moodleintegration_courses_moodleintegration_grades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodleintegration',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='moodleintegration',
            name='grades',
        ),
        migrations.AddField(
            model_name='moodleintegration',
            name='last_sync',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='MoodleCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('shortname', models.CharField(max_length=100)),
                ('category_id', models.IntegerField()),
                ('moodle_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='integrations.moodleintegration')),
            ],
        ),
        migrations.CreateModel(
            name='MoodleGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=255)),
                ('grade', models.FloatField(blank=True, null=True)),
                ('max_grade', models.FloatField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='integrations.moodlecourse')),
                ('moodle_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='integrations.moodleintegration')),
            ],
        ),
    ]
